apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  type: NodePort