resources:
  - ../../base/mysql
  - ../../base/wordpress 
   

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wp-deploy
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
