resources:
  - ../../base/mysql
  - ../../base/wordpress 


patches:
  - target: 
      group: apps 
      version: v1 
      kind: Deployment 
      name: mysql-deployment
    patch: |
      - op: replace 
        path: /spec/template/spec/containers/0/image
        value: mysql